### ISSUE TITLE
Typo in zping readme

### ISSUE THREAD

**Issue by gberl002** [openziti/sdk-golang#309]
In the intro section measurement is misspelled as `measurment`

**Comment by dissyulina** [comment]
Hi, I would like to work on this. Can you please assign me?

**Comment by imran1509** [comment]
Hey Can i work on this?

**Comment by dovholuknf** [comment]
All you need to do is fork it and put the pr up. Thanks! Since you both commented, whomever puts the PR up first can have it. Please ensure you have signed commits setup so we can accept the PR. Thanks

**Comment by dissyulina** [comment]
Hi, I've fixed the typo, but  been having difficulties in applying the signed commits for days. Is it a must to have a signed commit? If yes, I'll have to back down then :)
