### ISSUE TITLE
make end-to-end encryption configurable 

### ISSUE THREAD

**Issue by ekoby** [openziti/sdk-golang#35]
this needs more thinking/definition
some ideas:
* configuration option to disallow non-encrypted fallback
* specify no encryption

**Comment by andrewpmartinez** [comment]
This should be closed now.

Services can have e2e required or not. The edge routers enforce the configuration. If it is required and the connecting SDK or hosting SDK/router does not support e2e it refuses to connect the client and host. If e2e is optional, e2e will be established if possible and if not fallback.

**Comment by ekoby** [comment]
fixed in #89

**Comment by ekoby** [comment]
fixed in #89
