### ISSUE TITLE
HTTP calls should respect environment proxy settings

### ISSUE THREAD

**Issue by plorenz** [openziti/sdk-golang#436]

**Comment by bennyandresen** [comment]
Can this be extended for connectEdgeRouter in `ziti.go`? Based on the commits in this issue enroll requests were proxified.

**Comment by plorenz** [comment]
> Can this be extended for connectEdgeRouter in `ziti.go`? Based on the commits in this issue enroll requests were proxified.

See https://github.com/openziti/sdk-golang/issues/663 for how to control proxy selection for edge routers.

**Comment by qrkourier** [comment]
relates to https://github.com/openziti/ziti/issues/641
